apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mongodb-ebs-gp3
  # namespace: backend-database-tier
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp3
  fsType: ext4