apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: my-frontend-deployment #THIS IS LABEL OF POD GIVEN IN deployment-pod.yml ## match the label on your frontend Pods
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000 # internal cluster port
      targetPort: 3000 # container port in the frontend Pod
      nodePort: 31000 # port to access on your localhost
